export default {
    SET_FETCH_REQUEST_PENDING: "SET_FETCH_REQUEST_PENDING",
    SET_FETCH_REQUEST_FULFILLED: "SET_FETCH_REQUEST_FULFILLED",
    SET_FETCH_REQUEST_REJECTED: "SET_FETCH_REQUEST_REJECTED"
  }